# DATABASE CONFIGURATION
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/effitrack_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# SECURITY
effitrack.app.secret=${JWT_SECRET}
effitrack.app.expirationMs=${JWT_EXPIRATION}
# APP
app.master.pin=${MASTER_PIN_CODE}
