spring.profiles.active=dev
spring.config.import=optional:file:.env[.properties]
# APPLICATION SETTINGS
spring.application.name=effitrack-server
server.port=${PORT:8080}
# EMAIL SETTINGS
spring.mail.host=smtp.gmail.com
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USER}
spring.mail.password=${EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
gemini.api.key=${API_KEY}